marts:
  - name: civics
    description: "Analytics mart for entities related to elections and elected offices"

  - name: mban2026
    description: "Mart for DEID voter data for 2026 MBAN students"

